### ISSUE TITLE
[Bug] Retrieval Issues

### ISSUE THREAD

**Issue by ThakerKush** [Dhravya/supermemory#105]
List of issues I came across which are related to retrieval:

1. The model sometimes gives content that probably shouldn't be displayed to the users like the context and '<context_score>' tags:
 
![PHOTO-2024-07-03-20-41-51](https://github.com/Dhravya/supermemory/assets/89926467/0528be1a-ac3b-4ad1-a264-8bf24cfd327f)

2. Retrieval system does not get data form large twitter posts or huge webpages, also cloud flare error messages seem to be provided as context to the model based on how it responds 

![PHOTO-2024-07-03-20-51-02](https://github.com/Dhravya/supermemory/assets/89926467/c590a8ac-c8f8-4326-8162-a5da56012b46)

also there maybe in-sufficient context given to the model based on this response:

![image](https://github.com/Dhravya/supermemory/assets/89926467/3cbe5f6d-e4ce-443c-afdb-770aed2fb554)
^^The answer to this was in the given essay [here](https://arc.net/l/quote/sccceoed)

sometimes answering an entirely un-related question 
![PHOTO-2024-07-05-00-15-20](https://github.com/Dhravya/supermemory/assets/89926467/492b6587-5b35-4716-aa14-589fcb7839cf)

3. Related memories section also shows un-related memories ( as you can see in the image above where it has the essay and also a tweet about downtime )

**Comment by Dhravya** [comment]
Thanks for the issues! 
1 is likely because of the way the prompt is formatted, I just pushed out a fix that should do it. can you try?
2. For some reason the [markdowner](https://md.dhr.wtf) service had crashed. I also found that I should probably follow the links for redirects in markdowner, I'll change it accordingly
3. Third and fourth issue is also likely because of markdowner going down
4. Yeah, showing unrelated memories was a design decision- Because there's no reliable, "full-proof" way of telling what's contextual and what's not, I just decided to show everything to the user so that they can find relevant info easily too.

**Comment by Dhravya** [comment]
Except the redirect following, all of these should be fixed now

**Comment by Dhravya** [comment]
I've made it so that it follows redirects now, closing the issue now, thanks again
