### ISSUE TITLE
Suggestion: Provide a button for batch import browser bookmark URLs

### ISSUE THREAD

**Issue by littlemoji** [Dhravya/supermemory#23]
Provide a button for batch import browser bookmark URLs
Chrome browser(almost all mainstream browsers ) bookmarks are exported as an HTML file, so i think we can get the URLs by reading all the href attributes of `<a>` tag.

**Comment by Dhravya** [comment]
Amazing idea. it's planned! Anyone wanna work on this one?

**Comment by littlemoji** [comment]
is  `chrome.runtime.sendMessage({ type: "urlChange", content, url, spaces });` this function send data to api ? 
Since browser bookmarks may only provide URLs, what do `type`, `content`, and `spaces` signify?

**Comment by littlemoji** [comment]
If the outcomes of the Q&A are based on the content from the method mentioned above, and given that the pages linked by the URLs might change, should users be allowed to set how frequently the content from these links is updated?

**Comment by Dhravya** [comment]
Hi!
Yes, `chrome.runtime.sendMessage({ type: "urlChange", content, url, spaces })` is the function that sends data to the API. 
Naming is weird because earlier it used to be something else! haha
We'll need one more function to send the URL only (And then render a browser to get the contents using browser rendering maybe)

> what do type, content, and spaces signify?

In chrome extensions, the client and 'background script' (that can send requests to the API and store sensitive information like user credentials) communicate using something called "messages"
messages are distinguished by 'types'. in the background script, there's a message listener and an if-else statement that basically filters the type to run a specific piece of code with some information (`content` and `spaces`)
hope that helps!
